language: python
env:
  - TOXENV=py26-django16
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py34-django17
install:
  - pip install tox
script: tox
notifications:
  irc: "irc.freenode.org#opps"
  slack: yacows:Dm0D2qLJnx8e7Ax7JfIcPLry
  on_success: "never"
after_success:
  - coveralls
