language: python
python:
  - "2.7"
services:
  - redis-server
env:
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
install:
  - pip install tox
script: make tox
notifications:
  irc: "irc.freenode.org#opps"
  slack: yacows:Dm0D2qLJnx8e7Ax7JfIcPLry
  on_success: "never"
after_success:
  - coveralls
