language: python
python:
  - "2.7"
services:
  - redis-server
env:
  - DJANGO=django==1.6
  - DJANGO=django==1.7
install:
  - pip install $DJANGO
  - make install
script: make test
notifications:
  irc: "irc.freenode.org#opps"
  slack: yacows:Dm0D2qLJnx8e7Ax7JfIcPLry
  on_success: "never"
after_success:
  - coveralls
